name: 'Storybook Tests'
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook -w ./packages/app
#      - name: Serve Storybook and run tests
#        run: |
#          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
#            "npx http-server storybook-static --port 6006" \
#            "npx wait-on http-get://127.0.0.1:6006 && npm run test-storybook -w ./packages/app"